# Generated by Django 3.1.3 on 2020-12-28 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov'], 'Only mp4 and mov files are allowed')]),
        ),
    ]
